### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by olexandr-konovalov** [MWhybrow92/MajoranaAlgebras#37]
Could you please add these details?

**Comment by olexandr-konovalov** [comment]
These are added to the manual, but it's a good practice to have a plain text file in the root directory of the package, so interested parties can find that information easily. See some examples in packages from https://github.com/gap-packages/

**Comment by MWhybrow92** [comment]
Now also fixed!

**Comment by olexandr-konovalov** [comment]
Thanks - did you forget to push ;) ?

**Comment by MWhybrow92** [comment]
The license file is already in the version 1.3 archive file but I have now also pushed it to master branch
