### ISSUE TITLE
Emtpy chapters in the manual

### ISSUE THREAD

**Issue by olexandr-konovalov** [MWhybrow92/MajoranaAlgebras#44]
These chapters do not have any content:
2 Shapes of a Majorana representation
3 Majorana representations
4 Functions for calculating with Majorana representations

**Comment by MWhybrow92** [comment]
Fixed with help from @ChrisJefferson

**Comment by olexandr-konovalov** [comment]
Thanks @MWhybrow92 - are you going to publish a new release then?
